### ISSUE TITLE
Context Menu plugin on trac-hacks is too old, we need to update it from our internal repo.

### ISSUE THREAD

**Issue by pipern** [CGI-define-and-primeportal/trac-plugin-sharepoint#1]
```
2015-05-07 15:04:21,872 Trac[loader] ERROR: Skipping "tracsharepoint.browser = tracsharepoint.browser": 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/trac/loader.py", line 68, in _load_eggs
    entry.load(require=True)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/vagrant/tracsharepoint/browser.py", line 7, in <module>
    from contextmenu.contextmenu import SubversionLink, ISourceBrowserContextMenuProvider, is_subversion_repository
ImportError: cannot import name is_subversion_repository
```

**Comment by pipern** [comment]
I've pushed our internal history to https://github.com/CGI-define-and-primeportal/trac-plugin-contextmenuplugin
